# -*- coding: utf-8 -*-
"""uzGPT_bot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NzqQNfqO4EuDWbhpjdeH90KOx-wHYvTD
"""

import openai
import telebot
import time

openai.api_key = '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'
messages = [
    {"role": "system", "content": "speak only in Uzbek, only."},
]

TOKEN = '6165875867:AAFDuV4nO5WBEKMb7jXJmTdAJpVjj3csh-0'
bot = telebot.TeleBot(TOKEN, parse_mode=None)

@bot.message_handler(commands=['start'])
def send_welcome(message):
    javob = "Salom Men sun'iy intellektman!"
    javob += "\n Sizga qanday yordam bera olaman?"
    bot.reply_to(message, javob)







@bot.message_handler(commands=['help'])
def send_welcome(message):
    javob ='''Assalomu alaykum. Men openAI tomonidan tarbiyalangan suniy intellektman. 
    Siz men bilan gaplashishingiz va istalgan savolingizni berishingiz mumkin, lekin
    o'zbek tilini endi o'rganyapman. Xatoliklar bo'lsa oldindan uzr.

    Yo'ldashev Muhammadyusuf bu botni yaratdi. U va uning oilasi haqqiga duoda bo'ling.'''
    bot.reply_to(message, javob)



@bot.message_handler(func=lambda m: True)
def echo_all(message):
    text = message.text
    if message:
        messages.append(
            {"role": "user", "content": text},
        )
        bot.send_chat_action(message.chat.id, 'typing')
        chat = openai.ChatCompletion.create(
            model="gpt-3.5-turbo", messages=messages
        )
        
        
    
    bot.send_chat_action(message.chat.id, 'typing')
    time.sleep(1)
    javob = chat.choices[0].message.content
    messages.append({"role": "assistant", "content": javob})
    bot.reply_to(message, javob)
bot.infinity_polling()